assetic:
    assets:
        angular_growl_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-growl-v2/build/angular-growl.css'
        main_css:
            inputs:
                - '@RealtimeNotesBundle/Resources/public/css/*'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../bower_components/bootstrap/dist/css/bootstrap.css'
        img_bootstrap_glyphicons_woff:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.woff'
            output: 'bootstrap/glyphicons-halflings-regular.woff'
        img_bootstrap_glyphicons_svg:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.svg'
            output: 'bootstrap/glyphicons-halflings-regular.svg'
        img_bootstrap_glyphicons_eot:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.eot'
            output: 'bootstrap/glyphicons-halflings-regular.eot'
        img_bootstrap_glyphicons_ttf:
            inputs:
                -  '%kernel.root_dir%/../web/fonts/glyphicons-halflings-regular.ttf'
            output: 'bootstrap/glyphicons-halflings-regular.ttf'