assetic:
    assets:
        main_scripts_js:
            inputs:
                - '%kernel.root_dir%/../ux/js/scripts.js'
        jquery_js:
             inputs:
                - '%kernel.root_dir%/../bower_components/jquery/dist/jquery.js'
        angular_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular/angular.js'
        angular_route_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-route/angular-route.js'
        angular_growl_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-growl-v2/build/angular-growl.min.js'
        angular_bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../bower_components/angular-bootstrap/ui-bootstrap.js'
                - '%kernel.root_dir%/../bower_components/angular-bootstrap/ui-bootstrap-tpls.js'
        realtime_app_js:
            inputs:
                - '@RealtimeNotesBundle/Resources/public/js/*'
                - '@RealtimeNotesBundle/Resources/public/js/*/*'