realtime_notes_homepage: #Symfony
    path:     /index
    defaults: { _controller: RealtimeNotesBundle:ToDoList:index }

realtime_notes_get: #Angular REST
    path: /notes
    defaults: { _controller: RealtimeNotesBundle:ToDoList:get }
    methods: [GET]

realtime_notes_post: #Angular REST
    path: /notes
    defaults: { _controller: RealtimeNotesBundle:ToDoList:save }
    methods: [POST]
    
realtime_notes_test:
    path: /notes/test
    defaults: { _controller: RealtimeNotesBundle:ToDoList:test }